name: justlog
main: index.js
version: 0.1.1
description: 'a powerful log libs'
author:
  name: q3boy
  email: q3boy1@gmail.com
engines:
  node: >=0.8.0
homepage: https://github.com/q3boy/justlog
repository:
  type: git
  url: git://github.com/q3boy/justlog.git
bugs:
  url: https://github.com/q3boy/justlog/issues
dependencies:
  options-stream : '*'
  mkdirp : '*'
  moment : '*'
  event-pipe: '*'
devDependencies:
  coffee-script: '*'
  mocha: '*'
  expect.js: '*'
  jscover: '*'
  yamljs: '0.1.6'
scripts:
  prepublish: make release
  postpublish: make clean
  test: make test-cov
